#!/bin/bash

# Obfuscate the obfuscator as a torture test

../pyobfuscate ../pyobfuscate > pyobfuscate
chmod u+x pyobfuscate

for fn in test_*.py; do
  echo "Running ${fn}"
	python ./pyobfuscate $fn | python -
done
